# Nixpacks Configuration for Railway Deployment
[phases.setup]
nixPkgs = ['nodejs-18_x', 'python311', 'python311Packages.pip', 'python311Packages.virtualenv']

[phases.install]
cmds = [
    'npm ci',
    'python3 -m venv .venv',
    '. .venv/bin/activate && pip install --upgrade pip',
    '. .venv/bin/activate && pip install -r requirements.txt'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = '. .venv/bin/activate && npm run railway:start'