# Railway Configuration - Next.js Frontend Only
[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "${PORT}"
NIXPACKS_NODE_VERSION = "18"