# Railway Configuration for Cival Trading Dashboard
[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_PYTHON_VERSION = "3.11"
PORT = "3000"
REDIS_URL = "redis://default:6kGX8jsHE6gsDrW2XYh3p2wU0iLEQWga@redis-13924.c256.us-east-1-2.ec2.redns.redis-cloud.com:13924"
NEXT_PUBLIC_API_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
DATABASE_URL = "${DATABASE_URL}"