# Cival Dashboard Railway Configuration
# Monorepo deployment with Next.js frontend and Python backend

[build]
builder = "nixpacks"
buildCommand = "npm ci && python3 -m venv venv && source venv/bin/activate && pip install --no-cache-dir -r requirements.txt && npm run build"

[deploy]
startCommand = "source venv/bin/activate && npm run railway:start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_PYTHON_VERSION = "3.11"
REDIS_URL = "redis://default:6kGX8jsHE6gsDrW2XYh3p2wU0iLEQWga@redis-13924.c256.us-east-1-2.ec2.redns.redis-cloud.com:13924"
NEXT_PUBLIC_API_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"
DATABASE_URL = "${{DATABASE_URL}}"